openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
  description: Example API
servers:
  - url: https://api.example.com
paths:
  /internal-endpoint:
    post:
      x-internal: true
      summary: Create sensitive data (internal)
      operationId: createSensitiveData
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sensitiveField:
                  x-internal: true
                  type: string
                  description: Sensitive field; internal use only
                publicField:
                  type: string
                  description: Field visible to the public
              required:
                - sensitiveField
                - publicField
      responses:
        '201':
          description: Sensitive data created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      publicField:
                        type: string
                      sensitiveField:
                        x-internal: true
                        type: string
              example:
                status: created
                data:
                  id: 10
                  publicField: Visible Data
                  sensitiveField: This should be removed
  /mixed-endpoint:
    put:
      summary: Update mixed data with public and internal fields
      operationId: updateMixedData
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                updateField:
                  type: string
                  description: A public field to be updated
                hiddenField:
                  x-internal: true
                  type: string
                  description: A field that is internal
                nestedObject:
                  type: object
                  properties:
                    nestedPublic:
                      type: string
                      description: Public nested field
                    nestedInternal:
                      x-internal: true
                      type: string
                      description: Internal nested field
              required:
                - updateField
      responses:
        '200':
          description: Update successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  updateField:
                    type: string
                  hiddenField:
                    x-internal: true
                    type: string
                  nestedObject:
                    type: object
                    properties:
                      nestedPublic:
                        type: string
                      nestedInternal:
                        x-internal: true
                        type: string
              example:
                updateField: Updated value
                hiddenField: This should be removed
                nestedObject:
                  nestedPublic: Public nested value
                  nestedInternal: This nested internal value should be removed
  /public-endpoint:
    get:
      summary: Retrieve public data
      operationId: getPublicData
      responses:
        '200':
          description: Successful response with public data
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: Public identifier
                  name:
                    type: string
                    description: Name of the item
                  internalNote:
                    x-internal: true
                    type: string
                    description: An internal note that should be removed
                  details:
                    type: object
                    properties:
                      description:
                        type: string
                        description: Detailed description of the item
                      secretDetail:
                        x-internal: true
                        type: string
                        description: Internal secret detail, not public
              example:
                id: 1
                name: Public Item
                internalNote: This note should be filtered out
                details:
                  description: This is a public item description.
                  secretDetail: This secret should be removed
components: {}
